[build]
  command = "npm run build"
  functions = "src/functions"
  publish = "dist"


[[redirects]]
  from = "/api/hello/:name"
  to = "/.netlify/functions/hello?name=:name"
  status = 200


[[redirects]]
  from = "/*"
  to = "https://eqtventures.com/:splat"
  status = 200
